name: lesson_two
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'
environment:
  sdk: '>=2.18.0-234.0.dev <3.0.0'

dependencies:
  intl: ^0.17.0
  path: ^1.8.2
  teledart: ^0.3.4
  equatable: ^2.0.3
  meta: ^1.8.0
  stream_channel: ^2.1.0
  mockito: ^5.3.0
  mocktail: ^0.3.0


  my_library:
    path: "../my_library"


  my_library_dart:
    git:
      url: https://github.com/axiydev/my_library_dart.git
      ref: master
  uuid: ^3.0.6


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
  build_runner: ^2.2.0
