name: lesson_two
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  path: ^1.8.2
  teledart: ^0.3.4
  equatable: ^2.0.3
  meta: ^1.8.0
  stream_channel: ^2.1.0
  
  my_library:
    path: "../my_library"


  my_library_dart:
    git:
      url: https://github.com/axiydev/my_library_dart.git
      ref: master


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
